## Assembly - UnityScript

import os
import shutil

def post(bld):
	distdir = os.path.join(bld.top_dir, 'marsxplr_build', 'Mars Explorer_Data')
	os.makedirs(distdir, exist_ok=True)
	shutil.copy(
		os.path.join(bld.out_dir, 'Assembly_-_UnityScript', '58cc2f0ae478d40e7a89c7ba576c3586.dll'),
		os.path.join(distdir, 'Assembly - UnityScript.dll'))

def build(bld):
	bld.add_post_fun(post)
	
	bld(
		source=bld.path.ant_glob(os.path.join('src', '*.cs')),
		target='58cc2f0ae478d40e7a89c7ba576c3586.dll',
		rule='"${MCS}" -recurse:\"' +
			os.path.join(bld.path.abspath(), 'src', '*.cs') +
			'\" -reference:\"' + str(os.path.join(bld.out_dir, 'UnityEngine', 'UnityEngine.dll')) +
			'\" -reference:\"' + str(os.path.join(bld.out_dir, 'Assembly_-_CSharp_-_first_pass', '26998b3a9cbf54825a27e5f2d3cc4df1.dll')) +
			'\" -out:${TGT} -target:library ${MONOOPTS}')