import os
import shutil

APPNAME = 'MarsXPLR'
VERSION = '4.0.1'

top = '.'
out = 'wafbuild'

def options(ctx):
	ctx.add_option('--mono_home',
		action='store',
		default='',
		help='path where a mono install contains bin, lib, and include directories')

def configure(ctx):
	ctx.env.MONO_HOME = ctx.options.mono_home
	ctx.find_program('mcs',
		var='MCS',
		path_list=[os.path.join(ctx.env.MONO_HOME, 'bin')])

def build(bld):
	bld.env.MBUILD = os.path.join(bld.top_dir, 'marsxplr_build')

	if bld.cmd == 'clean':
		if os.path.exists(bld.env.MBUILD):
			shutil.rmtree(bld.env.MBUILD)
		return	

	bld.recurse('UnityDomainLoad')