## UnityDomainLoad

import os
import shutil

def post(bld):
	distdir = os.path.join(bld.top_dir, 'marsxplr_build', 'Mars Explorer_Data', 'lib')
	os.makedirs(distdir, exist_ok=True)
	shutil.copy(
		os.path.join(bld.out_dir, 'UnityDomainLoad', 'UnityDomainLoad.exe'),
		os.path.join(distdir, 'UnityDomainLoad.exe'))

def build(bld):
	bld.add_post_fun(post)
	
	bld(
		source=bld.path.ant_glob(os.path.join('src', '*.cs')),
		target='UnityDomainLoad.exe',
		rule='"${MCS}" -recurse:\"' +
			os.path.join(bld.path.abspath(), 'src', '*.cs') +
			'\" -out:${TGT} -target:exe ${MONOOPTS}')