## Assembly - CSharp - first pass

import os
import shutil

def post(bld):
	global outdir
	global out
	shutil.move(out, os.path.join(outdir, 'Assembly - CSharp - first pass.dll'))

def build(bld):
	bld.add_post_fun(post)

	level = bld.path.abspath()
	SOURCES = \
		os.path.join(level, 'Properties', 'AssemblyInfo.cs') + ' ' + \
		os.path.join(level, '*.cs')
	
	global outdir
	outdir = os.path.join(bld.env.MBUILD, 'Mars Explorer_Data')
	if not os.path.exists(outdir):
		os.makedirs(outdir)
	global out
	out = os.path.join(outdir, '26998b3a9cbf54825a27e5f2d3cc4df1')
	
	bld(rule='\"${MCS}\" ' +
		SOURCES +
		' -out:\"' + out +
		'\" -sdk:' + bld.env.MONOSDK +
		' -langversion:' + bld.env.MONOLANGVERSION +
		' -target:library'
		' -reference:\"' + bld.env.REF_UnityEngine + '\"')