AR = ['C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\LIB.exe']
ARFLAGS = ['/nologo']
AR_TGT_F = '/OUT:'
BINDIR = 'C:\\Users\\human\\AppData\\Local\\Temp/bin'
CC = ['C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe']
CCLNK_TGT_F = '/OUT:'
CC_NAME = 'msvc'
CC_SRC_F = ''
CC_TGT_F = ['/FC', '/c', '/Fo']
CFLAGS = ['/nologo']
CFLAGS_CRT_MULTITHREADED = ['/MT']
CFLAGS_CRT_MULTITHREADED_DBG = ['/MTd']
CFLAGS_CRT_MULTITHREADED_DLL = ['/MD']
CFLAGS_CRT_MULTITHREADED_DLL_DBG = ['/MDd']
CFLAGS_cshlib = []
CL = ''
COMPILER_CC = 'msvc'
CPPPATH_ST = '/I%s'
CXX = ['C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe']
CXXFLAGS = ['/nologo']
CXXFLAGS_CRT_MULTITHREADED = ['/MT']
CXXFLAGS_CRT_MULTITHREADED_DBG = ['/MTd']
CXXFLAGS_CRT_MULTITHREADED_DLL = ['/MD']
CXXFLAGS_CRT_MULTITHREADED_DLL_DBG = ['/MDd']
CXXFLAGS_cxxshlib = []
CXXLNK_TGT_F = '/OUT:'
CXX_NAME = 'msvc'
CXX_SRC_F = ''
CXX_TGT_F = ['/FC', '/c', '/Fo']
DEFINES_ST = '/D%s'
DEST_BINFMT = 'pe'
DEST_CPU = 'amd64'
DEST_OS = 'win32'
IMPLIB_ST = '/IMPLIB:%s'
INCLUDES = ['C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.36.32532\\include', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.36.32532\\ATLMFC\\include', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Auxiliary\\VS\\include', 'C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.22000.0\\ucrt', 'C:\\Program Files (x86)\\Windows Kits\\10\\\\include\\10.0.22000.0\\\\um', 'C:\\Program Files (x86)\\Windows Kits\\10\\\\include\\10.0.22000.0\\\\shared', 'C:\\Program Files (x86)\\Windows Kits\\10\\\\include\\10.0.22000.0\\\\winrt', 'C:\\Program Files (x86)\\Windows Kits\\10\\\\include\\10.0.22000.0\\\\cppwinrt', 'C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.8\\include\\um']
LIBDIR = 'C:\\Users\\human\\AppData\\Local\\Temp/lib'
LIBPATH = ['C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.36.32532\\lib\\x64', 'C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.8\\lib\\um\\x64', 'C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.22000.0\\ucrt\\x64', 'C:\\Program Files (x86)\\Windows Kits\\10\\\\lib\\10.0.22000.0\\\\um\\x64', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.36.32532\\lib\\x64', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.36.32532\\lib\\x86\\store\\references', 'C:\\Program Files (x86)\\Windows Kits\\10\\UnionMetadata\\10.0.22000.0', 'C:\\Program Files (x86)\\Windows Kits\\10\\References\\10.0.22000.0', 'C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319']
LIBPATH_ST = '/LIBPATH:%s'
LIB_ST = '%s.lib'
LINKFLAGS = ['/nologo', '/MANIFEST']
LINKFLAGS_cshlib = ['/DLL']
LINKFLAGS_cstlib = []
LINKFLAGS_cxxshlib = ['/DLL']
LINK_CC = ['C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\LINK.exe']
LINK_CXX = ['C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\LINK.exe']
MCS = ['C:\\Program Files\\Mono\\bin\\mcs.bat']
MONOINC = 'C:\\Program Files\\Mono\\include\\mono-2.0'
MONO_HOME = 'C:\\Program Files\\Mono'
MSVC_COMPILER = 'msvc'
MSVC_MANIFEST = True
MSVC_VERSION = 17.6
MT = ['C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.22000.0\\\\x64\\MT.exe']
MTFLAGS = ['/nologo']
PATH = ['C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\Common7\\IDE\\VC\\VCPackages', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\MSBuild\\Current\\bin\\Roslyn', 'C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v10.0A\\bin\\NETFX 4.8 Tools\\x64\\', 'C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.22000.0\\\\x64', 'C:\\Program Files (x86)\\Windows Kits\\10\\bin\\\\x64', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\\\MSBuild\\Current\\Bin\\amd64', 'C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\Common7\\IDE\\', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\Common7\\Tools\\', 'C:\\Program Files\\Mono\\bin\\', 'C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\java8path', 'C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath', 'C:\\Program Files\\OpenLogic\\jre-22.0.2.9-hotspot\\bin', 'C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\Program Files (x86)\\Intel\\OpenCL SDK\\2.0\\bin\\x86', 'C:\\Program Files (x86)\\Intel\\OpenCL SDK\\2.0\\bin\\x64', 'C:\\Program Files\\Git\\cmd', 'C:\\Program Files\\PuTTY\\', 'C:\\Program Files\\dotnet\\', 'C:\\Program Files (x86)\\GtkSharp\\2.12\\bin', 'C:\\Users\\human\\AppData\\Local\\Programs\\Python\\Python38\\Scripts\\', 'C:\\Users\\human\\AppData\\Local\\Programs\\Python\\Python38\\', 'C:\\Users\\human\\.dotnet\\tools', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\Ninja', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\Common7\\IDE\\VC\\Linux\\bin\\ConnectionManagerExe']
PREFIX = 'C:\\Users\\human\\AppData\\Local\\Temp'
RELEASE_PROFILE = 'no'
SELF_HOSTED = 'no'
STLIBPATH_ST = '/LIBPATH:%s'
STLIB_ST = '%s.lib'
WINRC = ['C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.22000.0\\\\x64\\RC.exe']
WINRC_SRC_F = ''
WINRC_TGT_F = '/fo'
cprogram_PATTERN = '%s.exe'
cshlib_PATTERN = '%s.dll'
cstlib_PATTERN = '%s.lib'
cxxprogram_PATTERN = '%s.exe'
cxxshlib_PATTERN = '%s.dll'
cxxstlib_PATTERN = '%s.lib'
def_PATTERN = '/def:%s'
implib_PATTERN = '%s.lib'
