import os

def build(bld):
	level = bld.path.abspath()
	SOURCES = \
		os.path.join(level, 'Properties', 'AssemblyInfo.cs') + ' ' + \
		os.path.join(level, 'UnityEngine', 'UnityDomainLoad.cs')

	outdir = os.path.join(bld.env.MBUILD, 'Mars Explorer_Data', 'lib')
	if not os.path.exists(outdir):
		os.makedirs(outdir)
	out = os.path.join(outdir, 'UnityDomainLoad.exe')
	
	bld(rule='\"${MCS}\" ' + SOURCES + ' -out:\"' + out + '\" -sdk:2 -langversion:3 -target:exe')