## UnityEngine

import os
import shutil

def post(bld):
	distdir_m = os.path.join(bld.top_dir, 'marsxplr_build', 'Mars Explorer_Data', 'lib')
	os.makedirs(distdir_m, exist_ok=True)
	shutil.copy(
		os.path.join(bld.out_dir, 'UnityEngine', 'UnityEngine.dll'),
		os.path.join(distdir_m, 'UnityEngine.dll'))
	distdir_r = os.path.join(bld.top_dir, 'ripper_build', 'Mars Explorer_Data', 'lib')
	os.makedirs(distdir_r, exist_ok=True)
	shutil.copy(
		os.path.join(bld.out_dir, 'UnityEngine', 'UnityEngine.dll'),
		os.path.join(distdir_r, 'UnityEngine.dll'))
	distdir_e = os.path.join(bld.top_dir, 'editor_build', 'Mars Explorer_Data', 'lib')
	os.makedirs(distdir_e, exist_ok=True)
	shutil.copy(
		os.path.join(bld.out_dir, 'UnityEngine', 'UnityEngine.dll'),
		os.path.join(distdir_e, 'UnityEngine.dll'))
	

def build(bld):
	bld.add_post_fun(post)
	
	bld(
		source=bld.path.ant_glob(os.path.join('src', '*.cs')),
		target='UnityEngine.dll',
		rule='"${MCS}" -recurse:\"' +
			os.path.join(bld.path.abspath(), 'src', '*.cs') +
			'\" -out:${TGT} -target:library ${MONOOPTS} -unsafe')